data = [
    {"name": "Cristiano Ronaldo", "follower_count": 630, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 510, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 430, "description": "Singer and actress", "country": "USA"},
    {"name": "Dwayne Johnson", "follower_count": 410, "description": "Actor and former wrestler", "country": "USA"},
    {"name": "Kylie Jenner", "follower_count": 400, "description": "Reality TV star and businesswoman", "country": "USA"},
    {"name": "Kim Kardashian", "follower_count": 370, "description": "Reality TV star and entrepreneur", "country": "USA"},
    {"name": "Virat Kohli", "follower_count": 270, "description": "Cricketer", "country": "India"},
    {"name": "Zendaya", "follower_count": 190, "description": "Actress and singer", "country": "USA"},
    {"name": "Taylor Swift", "follower_count": 280, "description": "Singer-songwriter", "country": "USA"},
    {"name": "Ariana Grande", "follower_count": 360, "description": "Singer and actress", "country": "USA"},
    {"name": "Neymar Jr", "follower_count": 220, "description": "Footballer", "country": "Brazil"},
    {"name": "LeBron James", "follower_count": 160, "description": "Basketball player", "country": "USA"},
    {"name": "Billie Eilish", "follower_count": 110, "description": "Singer", "country": "USA"},
    {"name": "Katy Perry", "follower_count": 100, "description": "Singer", "country": "USA"},
    {"name": "Rihanna", "follower_count": 150, "description": "Singer and businesswoman", "country": "Barbados"},
    {"name": "Shakira", "follower_count": 130, "description": "Singer", "country": "Colombia"},
    {"name": "David Beckham", "follower_count": 95, "description": "Footballer", "country": "UK"},
    {"name": "Emma Watson", "follower_count": 85, "description": "Actress", "country": "UK"},
    {"name": "Chris Hemsworth", "follower_count": 110, "description": "Actor", "country": "Australia"},
    {"name": "Robert Downey Jr.", "follower_count": 105, "description": "Actor", "country": "USA"},
    {"name": "Tom Holland", "follower_count": 95, "description": "Actor", "country": "UK"},
    {"name": "Gal Gadot", "follower_count": 100, "description": "Actress", "country": "Israel"},
    {"name": "Shah Rukh Khan", "follower_count": 45, "description": "Actor", "country": "India"},
    {"name": "Amitabh Bachchan", "follower_count": 38, "description": "Actor", "country": "India"},
    {"name": "Hrithik Roshan", "follower_count": 50, "description": "Actor", "country": "India"},
    {"name": "Kendall Jenner", "follower_count": 290, "description": "Model and TV personality", "country": "USA"},
    {"name": "Jennifer Lopez", "follower_count": 250, "description": "Singer and actress", "country": "USA"},
    {"name": "Will Smith", "follower_count": 90, "description": "Actor and rapper", "country": "USA"},
    {"name": "Drake", "follower_count": 140, "description": "Rapper", "country": "Canada"},
    {"name": "Justin Bieber", "follower_count": 290, "description": "Singer", "country": "Canada"},
    {"name": "Ed Sheeran", "follower_count": 125, "description": "Singer-songwriter", "country": "UK"},
    {"name": "Miley Cyrus", "follower_count": 110, "description": "Singer and actress", "country": "USA"},
    {"name": "Priyanka Chopra", "follower_count": 90, "description": "Actress", "country": "India"},
    {"name": "Deepika Padukone", "follower_count": 80, "description": "Actress", "country": "India"},
    {"name": "Ranveer Singh", "follower_count": 75, "description": "Actor", "country": "India"},
    {"name": "Jason Statham", "follower_count": 35, "description": "Actor", "country": "UK"},
    {"name": "Keanu Reeves", "follower_count": 25, "description": "Actor", "country": "Canada"},
    {"name": "Emma Stone", "follower_count": 30, "description": "Actress", "country": "USA"},
    {"name": "Anushka Sharma", "follower_count": 70, "description": "Actress", "country": "India"},
    {"name": "MS Dhoni", "follower_count": 60, "description": "Cricketer", "country": "India"},
    {"name": "Sania Mirza", "follower_count": 15, "description": "Tennis player", "country": "India"},
    {"name": "Novak Djokovic", "follower_count": 14, "description": "Tennis player", "country": "Serbia"},
    {"name": "Roger Federer", "follower_count": 12, "description": "Tennis player", "country": "Switzerland"},
    {"name": "Lewis Hamilton", "follower_count": 35, "description": "F1 driver", "country": "UK"},
    {"name": "Conor McGregor", "follower_count": 50, "description": "MMA fighter", "country": "Ireland"},
    {"name": "Logan Paul", "follower_count": 30, "description": "YouTuber and boxer", "country": "USA"},
    {"name": "MrBeast", "follower_count": 90, "description": "YouTuber", "country": "USA"},
    {"name": "PewDiePie", "follower_count": 25, "description": "YouTuber", "country": "Sweden"},
    {"name": "Charli D'Amelio", "follower_count": 150, "description": "TikTok star", "country": "USA"},
    {"name": "Addison Rae", "follower_count": 88, "description": "TikTok star", "country": "USA"},
    {"name": "Zlatan Ibrahimović", "follower_count": 58, "description": "Footballer", "country": "Sweden"},
    {"name": "Gigi Hadid", "follower_count": 80, "description": "Model", "country": "USA"},
    {"name": "Bella Hadid", "follower_count": 75, "description": "Model", "country": "USA"},
    {"name": "Camila Cabello", "follower_count": 70, "description": "Singer", "country": "Cuba"},
    {"name": "Doja Cat", "follower_count": 85, "description": "Singer and rapper", "country": "USA"},
    {"name": "Snoop Dogg", "follower_count": 90, "description": "Rapper", "country": "USA"},
    {"name": "Bad Bunny", "follower_count": 110, "description": "Singer and rapper", "country": "Puerto Rico"},
    {"name": "Marshmello", "follower_count": 60, "description": "DJ and music producer", "country": "USA"},
    {"name": "Bruno Mars", "follower_count": 75, "description": "Singer", "country": "USA"},
]
